### ISSUE TITLE
ImportError: No module named pkg_resources from py2exe

### ISSUE THREAD

**Issue by jonnojohnson** [hgrecco/pyvisa#106]
I created an executable with py2exe but the exe fails with the following error when I import visa:
```
Traceback (most recent call last):
  File "my_script.py", line 60, in <module>
  File "visa.pyc", line 16, in <module>
  File "pyvisa\__init__.pyc", line 18, in <module>
ImportError: No module named pkg_resources
```
Info:
```
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda\python.exe
   Version:        2.7.7
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          Jun 11 2014 10:41:43 (#default)
   Unicode:        UCS2

PyVISA Version: 1.6.2.dev0

Backends:
   ni:
      Version: 1.6.2.dev0 (bundled with PyVISA)
      #1: C:\windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: Keysight Technologies
         Impl. Version: 1359258704
         Spec. Version: 5243136
      #2: C:\windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: Keysight Technologies
         Impl. Version: 1359258704
         Spec. Version: 5243136
   py:
      Version: 0.1.dev0
      ASRL INSTR:
         Please install PySerial to use this resource type.
         No module named serial
      TCPIP INSTR: Available
      USB INSTR: Available via PyUSB (1.0.0b1). Backend: N/A
```
Any thoughts how to fix this?

**Comment by hgrecco** [comment]
I am closing this for now. Feel free to reopen if necessary.
