### ISSUE TITLE
\v gets converted to vertical tab in the file path to the library? 

### ISSUE THREAD

**Issue by zhutineer** [hgrecco/pyvisa#208]
Hi, I've been up all night trying to get pyvisa working, and am currently stuck on the following: 

C:\Program Files (x86)\Python\Lib\site-packages>python getTrace.py
2016-03-17 06:28:55,072 - pyvisa - DEBUG - Could not open VISA wrapper <class 'pyvisa.ctwrapper.highlevel.NIVisaLibrary'>: C:\Windows\System32isa32.dll
Error while accessing C:\Windows\System32isa32.dll: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "getTrace.py", line 285, in <module>
    main()
  File "getTrace.py", line 34, in main
    resMgr      = visa.ResourceManager('C:\Windows\System32\visa32.dll')
  File "C:\Program Files (x86)\Python\Lib\site-packages\pyvisa\highlevel.py", line 1488, in __new__
    visa_library = open_visa_library(visa_library)
  File "C:\Program Files (x86)\Python\Lib\site-packages\pyvisa\highlevel.py", line 1460, in open_visa_library
    return cls(argument)
  File "C:\Program Files (x86)\Python\Lib\site-packages\pyvisa\highlevel.py", line 107, in __new__
    obj._init()
  File "C:\Program Files (x86)\Python\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 132, in _init
    raise errors.LibraryError.from_exception(exc, self.library_path)
pyvisa.errors.LibraryError: Error while accessing C:\Windows\System32 isa32.dll: [Error 126] The specified module could not be found

I think the error here is that \v is getting converted to a vertical tab symbol (it doesn't show up in the text formatted here, but that's what it looks like in command line.)

What do I do to fix this?

**Comment by zhutineer** [comment]
Ended up looking at this answer [(http://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found)] and then putting a 'r' before my file path.

```
import visa

def main():
    # Instantiate resource manager (use this line to change to visa library line)
    resMgr = visa.ResourceManager(r'C:\Windows\System32\visa32.dll')
```

This worked for me, I got all the things I expected out of it:

C:\Program Files (x86)\Python\Lib\site-packages>python getTrace.py
2016-03-17 06:40:30,088 - pyvisa - DEBUG - viFindRsrc(41865128L, u'GPIB?*INSTR', '<ViObject object at 0x026FE490>', 'c_ulong(0L)', <ctypes.c_char_Array_256 object at 0x02C136C0>) -> -1073807343
No Instruments available. Terminating script.

2016-03-17 06:40:30,118 - pyvisa - DEBUG - User defined library files: [u'C:\\Users\\Jim\\.pyvisarc']
2016-03-17 06:40:30,141 - pyvisa - DEBUG - Automatically found library files: ['C:\\WINDOWS\\system32\\visa32.dll', 'C:\\WINDOWS\\system32\\visa32.dll']
2016-03-17 06:40:30,157 - pyvisa - DEBUG - Library signatures: 90 ok, 0 failed
2016-03-17 06:40:30,163 - pyvisa - DEBUG - Created library wrapper for C:\WINDOWS\system32\visa32.dll
2016-03-17 06:40:30,171 - pyvisa - DEBUG - viOpenDefaultRM('<ViObject object at 0x02C13940>',) -> 0
2016-03-17 06:40:30,178 - pyvisa - DEBUG - Created ResourceManager with session 41863904
2016-03-17 06:40:30,187 - pyvisa - DEBUG - viFindRsrc(41863904L, u'GPIB?*INSTR', '<ViObject object at 0x02C13940>', 'c_ulong(0L)', <ctypes.c_char_Array_256 object at 0x02C13990>) -> -1073807343
No Instruments available. Terminating script.

So good enough, I'm just gonna leave this here in case this helps someone.
